### PR TITLE
Use run instead of args to check whether we are watching

### PR DESCRIPTION
**Pull request by lloydho**
Use run instead of args to check whether we are watching.

### CODE REVIEW

**Comment by TiddoLangerak** [comment]
Looks good, but why did you change the exit code?

**Comment by lloydho** [comment]
My bad fixed.

**Comment by lloydho** [comment]
@TiddoLangerak ping

**Comment by TiddoLangerak** [comment]
I'm so sorry for taking this long to merge, got "slightly" per-occuppied. Will merge and publish this in a minute. Thanks for your contribution!

**Pull request merged**
